create table if not exists public.unclassified_theme_logs (
  id bigint generated by default as identity primary key,
  normalized_expression text not null unique,
  raw_expression text not null,
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  sources text[] not null default '{}',
  record_ids text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'mapped', 'excluded', 'deferred')),
  mapped_theme text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint mapped_theme_required check (status <> 'mapped' or mapped_theme is not null)
);

alter table public.unclassified_theme_logs enable row level security;

create or replace function public.record_unclassified_theme(
  p_raw_expression text,
  p_normalized_expression text,
  p_source text,
  p_record_ids text[] default '{}'
) returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.unclassified_theme_logs (
    normalized_expression,
    raw_expression,
    occurrence_count,
    sources,
    record_ids
  ) values (
    p_normalized_expression,
    p_raw_expression,
    greatest(coalesce(cardinality(p_record_ids), 0), 1),
    array[p_source],
    coalesce(p_record_ids, '{}'::text[])
  )
  on conflict (normalized_expression) do update set
    raw_expression = excluded.raw_expression,
    occurrence_count = public.unclassified_theme_logs.occurrence_count + greatest(coalesce(cardinality(excluded.record_ids), 0), 1),
    sources = coalesce((
      select array_agg(distinct value)
      from unnest(public.unclassified_theme_logs.sources || excluded.sources) as value
    ), '{}'::text[]),
    record_ids = coalesce((
      select array_agg(distinct value)
      from unnest(public.unclassified_theme_logs.record_ids || excluded.record_ids) as value
      where value <> ''
    ), '{}'::text[]),
    last_seen_at = now()
  where public.unclassified_theme_logs.status in ('pending', 'deferred');
end;
$$;

revoke all on table public.unclassified_theme_logs from anon, authenticated;
grant select, insert, update on table public.unclassified_theme_logs to service_role;
grant usage, select on sequence public.unclassified_theme_logs_id_seq to service_role;
